# Generated by Django 5.1 on 2025-09-20 17:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("speed", models.IntegerField(verbose_name="Скорость (км/ч)")),
                (
                    "magnetic",
                    models.IntegerField(
                        verbose_name="Еденицы измерения магнитного поля"
                    ),
                ),
                (
                    "scatter_area",
                    models.IntegerField(
                        verbose_name="Eденицы измерения площади разброса"
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="Персональная оценка")),
                (
                    "other_user_grade",
                    models.IntegerField(
                        verbose_name="Оценка другого пользователя (отправителя)"
                    ),
                ),
                ("user_id", models.UUIDField(verbose_name="ID пользователя")),
            ],
            options={
                "verbose_name": "Предупреждение",
                "verbose_name_plural": "Предупреждения",
                "db_table": "alarms",
            },
        ),
        migrations.CreateModel(
            name="DefaultAlarmConf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("speed", models.IntegerField(verbose_name="Скорость (км/ч)")),
                (
                    "magnetic",
                    models.IntegerField(
                        verbose_name="Еденицы измерения магнитного поля"
                    ),
                ),
                (
                    "scatter_area",
                    models.IntegerField(
                        verbose_name="Eденицы измерения площади разброса"
                    ),
                ),
                (
                    "speed_weight",
                    models.IntegerField(verbose_name="Скорость (км/ч) - вес"),
                ),
                (
                    "magnetic_weight",
                    models.IntegerField(
                        verbose_name="Еденицы измерения магнитного поля - вес"
                    ),
                ),
                (
                    "scatter_weight",
                    models.UUIDField(
                        verbose_name="Eденицы измерения площади разброса - вес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки предупреждений по умолчанию",
                "verbose_name_plural": "Настройки предупреждений по умолчанию",
                "db_table": "default_alarm_confs",
            },
        ),
        migrations.CreateModel(
            name="UserAlarmConf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "speed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Скорость (км/ч)"
                    ),
                ),
                (
                    "magnetic",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Еденицы измерения магнитного поля",
                    ),
                ),
                (
                    "scatter_area",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Eденицы измерения площади разброса",
                    ),
                ),
                (
                    "speed_weight",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Скорость (км/ч) - вес"
                    ),
                ),
                (
                    "magnetic_weight",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Еденицы измерения магнитного поля - вес",
                    ),
                ),
                (
                    "scatter_weight",
                    models.UUIDField(
                        blank=True,
                        null=True,
                        verbose_name="Eденицы измерения площади разброса - вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки предупреждений пользователя",
                "verbose_name_plural": "Настройки предупреждений пользователя",
                "db_table": "user_alarm_confs",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("9e09d664-5331-4d85-bcf5-0cf0a886ad9f"),
                unique=True,
                verbose_name="Уникальный код",
            ),
        ),
    ]
