# Generated by Django 5.1 on 2025-09-20 17:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0002_alarm_defaultalarmconf_useralarmconf_alter_user_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="magnetic",
            field=models.IntegerField(verbose_name="Магнитное поле"),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="scatter_area",
            field=models.IntegerField(verbose_name="Эффективное площадь рассеяния"),
        ),
        migrations.AlterField(
            model_name="defaultalarmconf",
            name="magnetic",
            field=models.IntegerField(verbose_name="Магнитное поле"),
        ),
        migrations.AlterField(
            model_name="defaultalarmconf",
            name="magnetic_weight",
            field=models.FloatField(verbose_name="Магнитного поле - вес"),
        ),
        migrations.AlterField(
            model_name="defaultalarmconf",
            name="scatter_area",
            field=models.FloatField(verbose_name="Эффективное площадь рассеяния"),
        ),
        migrations.AlterField(
            model_name="defaultalarmconf",
            name="scatter_weight",
            field=models.FloatField(verbose_name="Эффективное площадь рассеяния - вес"),
        ),
        migrations.AlterField(
            model_name="defaultalarmconf",
            name="speed_weight",
            field=models.FloatField(verbose_name="Скорость (км/ч) - вес"),
        ),
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("9d0cc21e-2898-4a7b-84b0-21816fb966f8"),
                unique=True,
                verbose_name="Уникальный код",
            ),
        ),
        migrations.AlterField(
            model_name="useralarmconf",
            name="magnetic",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Магнитное поле"
            ),
        ),
        migrations.AlterField(
            model_name="useralarmconf",
            name="magnetic_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Магнитного поле - вес"
            ),
        ),
        migrations.AlterField(
            model_name="useralarmconf",
            name="scatter_area",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Эффективное площадь рассеяния"
            ),
        ),
        migrations.AlterField(
            model_name="useralarmconf",
            name="scatter_weight",
            field=models.FloatField(
                blank=True,
                null=True,
                verbose_name="Эффективное площадь рассеяния - вес",
            ),
        ),
        migrations.AlterField(
            model_name="useralarmconf",
            name="speed_weight",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Скорость (км/ч) - вес"
            ),
        ),
    ]
