# Generated by Django 5.1 on 2025-09-20 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0003_alter_alarm_magnetic_alter_alarm_scatter_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="grade",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Персональная оценка"
            ),
        ),
        migrations.AlterField(
            model_name="alarm",
            name="other_user_grade",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Оценка другого пользователя (отправителя)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("077d975d-0e6f-403e-9e02-d4b1d39ee627"),
                unique=True,
                verbose_name="Уникальный код",
            ),
        ),
    ]
