# Generated by Django 5.1 on 2025-09-21 09:52

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models_app", "0004_alter_alarm_grade_alter_alarm_other_user_grade_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alarm",
            name="latitude",
            field=models.FloatField(default=0.0, verbose_name="Широта"),
        ),
        migrations.AddField(
            model_name="alarm",
            name="longitude",
            field=models.FloatField(default=0.0, verbose_name="Долгота"),
        ),
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.UUIDField(
                default=uuid.UUID("ee711d6e-bc5d-4353-b859-03371c1405a8"),
                unique=True,
                verbose_name="Уникальный код",
            ),
        ),
    ]
