# Generated by Django 5.2.6 on 2025-09-21 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0005_alarm_latitude_alarm_longitude_alter_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='ai_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано ИИ'),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_analyse_enabled',
            field=models.BooleanField(default=False, verbose_name='Включить анализ AI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.UUID('fc0f0dc8-d4e3-47e0-8958-2f5b54e09ab6'), unique=True, verbose_name='Уникальный код'),
        ),
    ]
