# Generated by Django 5.2.6 on 2025-09-21 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_alarm_ai_processed_user_ai_analyse_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.UUID('e36af55e-1a8b-4a29-972f-5ff45a0bf027'), unique=True, verbose_name='Уникальный код'),
        ),
    ]
